import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Navbar />

      <main>
        <section className={styles.heroBox}>
          <div className={`${styles["heroCard"]} ${"card"}`}>
            <img className={styles.heroLogo} src="/img/logo.jpg"></img>
            <h1>About Fostering</h1>
            <div className={`${"row"} ${styles["heroBtnRow"]}`}>
              <div className={`${"col-sm"}`}>
                <button className={`${"btn btn-primary"}  ${styles["heroBtn"]}`}>About</button>
              </div>
              <div className={`${"col-sm"}`}>
                <button className={`${"btn btn-primary"}  ${styles["heroBtn"]}`}>Contact Us</button>
              </div>

            </div>
          </div>
        </section>

        {/* ABOUT REACHNINGOUT*/}
        <section className={`${styles["aboutUs"]} ${"container"}`}>
        
        <div className={` ${styles["aboutTopCard"]}`}>
             <div className={`${styles["ourPhilosophyCopy"]}`}>
              <h1>What is Foster Care?</h1>
                <p>Foster care is a way of providing a family environment to a child who is not able to live with their birth family.  There are many reasons why a child may require foster care: relationship problems, a breakdown of the family unit, family illness or a situation in which a child’s welfare may be threatened in some way.</p>
                <p>In any of these situations, the Children’s Aid Society becomes involved to provide support to the child and family for the duration of the foster care placement which could last a few days, months or years.   When a child is in foster care, the legal responsibility lies with the Children’s Aid Society or in the case of a voluntary care agreement, with a birth parent.</p>
                <p>A “foster care placement” is when Reachingout Family Homes connects a child needing a home with an approved foster family in our program.  The placement may be short or long term and the child may be reunited with their birth family, be introduced to an adoptive family or may remain in foster care until they reach the age of independence.</p>
             </div>
             
            </div>
          <div className={`${styles["aboutFosteringSection"]}`}>
          
        
         

        
          
            <div className={`${styles["ourPhilosophy"]} ${styles["aboutCard1"]}`}>

              <div className={styles.ourPhilosophyCopy}>
                <h1>How Will it Affect My Family?</h1>
                <p>Becoming a foster family is a full time commitment not just for parents but for natural children as well.  Being a foster family can be an unbelievably rewarding experience however it can present challenges as well.</p>
                <p>Natural children will share their parents, their sibling, their toys and their home with the foster children.  Keep this in mind when making the decision to become a foster parent.  All members of your family must be supportive in order to be a successful foster family.  You should also discuss your decision with your extended family and friends as they will need to be supportive and understanding of your new family dynamic.</p>
              </div>
            </div>
        
          
            <div className={` ${styles["ourPhilosophy"]} ${styles["aboutCard2"]}`}>
            <div className={styles.ourPhilosophyCopy}>
            <h1>What is a Foster Parent?</h1>
                <p>Reachingout foster parents are part of a professional team whose overall goal is to meet the needs of children placed in their home.</p>
                <p>Becoming a foster parent is a full-time career which requires that one parent be at home full time.  Although children will attend school programs, it is necessary that a parent be available throughout the day should a child be unable to attend school, have an appointment or an emergency.</p>
                <p>As foster parents, you are responsible for ensuring regular medical and dental care.  You are also required to attend all meetings concerning the foster child(ren) living in your home.  These meetings may include psychological assessments, counselling appointments, school meetings or meetings with representatives of the Children’s Aid Society.</p>
            </div>
            </div>
          
          </div>
         
        </section>

        <section className={styles.support}>
          <div className={`${"container"} ${styles["support"]}`}>
            
              <div className="row">
             
                
                <div className="col-sm-8">
              <div className={`${styles["services"]} ${"card"}`}>
              
                <div className={styles.servicesCopy}>
                <h1>Fostering Reimbursement</h1>
              <p>Reachingout Family Homes provides a reimbursement to foster families to allow them to focus on supporting the young people in their home.</p>
              <p>The per diem a foster family receives covers the expenses of food, clothing, basic travel, household bills and everyday living expenses.  The per diem is determined when a child is placed in the home and is governed by our licensing agreement with the Ministry of Children and Youth Services and the needs of the child.  There will be additional expenses that a child may incur and such expenses will be the responsibility of the placing CAS agency.</p>
              <p>For further information regarding reimbursement contact our agency.</p>
                </div>
                </div>
                </div>
                <div className="col-sm-4">
                  <div className={`${styles["fosterCategoriesCard"]} ${"card"}`}>
                    <div className={styles.fosterCategoriesCopy}>
                      <h1>What Do We Provide Our Families?</h1>
                 
                <p>Reachingout offers three categories of foster homes:</p>
                <ul>
                  <li>Financial Reimbursement</li>
                  <li>Professional Support Worker</li>
                  <li>24 hour, 7 days a week on call support</li>
                  <li>Training and Education</li>
                </ul>
                <p>Each category provides services to its individual client group.</p>
                </div>
                </div>
                </div>
              </div>

              </div>
                
        </section>

        <section>
          <div>
              <div className={`${"container"} ${styles["mixedModality"]}`}>
             
                <div className="row">
                <div className="col-sm-6">
                 <div className={`${"card"} ${styles["contactCopy"]}`}>
                   <h1>Contact Us</h1>
                   <form
                      action="https://formspree.io/f/xayvrooa"
                      method="POST"
                      >
                      <label>
                        <p>Your email:</p>
                        <input type="email" name="email" />
                      </label>
                      <label>
                        Your message:
                      <textarea name="message"></textarea>
                    </label>

                  <button type="submit">Send</button>
                </form>
                 </div>
                    
                 </div>

                  <div className={`${"col-sm-6"} ${styles["mixedModalityCopy"]}`}>
                  <h1>Mixed Modality Program</h1>
                  <p>The goal of Reachingout Family Homes is to provide four treatment beds in each mixed modality home.  These beds are for children with emotional/behavioural disturbances and/or high medical needs.</p>
                  <p>The Mixed Modality program will operate with one full time Social Work staff that will oversee the running of the program. The support team will consist of a full time Child and Youth Worker who will be available to the home for forty hours per week – the time frame to be determined between the CYW and the Treatment Home parents.</p>
                  </div>
                </div>
                
              </div>
              </div>
        </section>      
             
      </main>


    </div>
  )
}


if (typeof window !== "undefined") {
  window.onscroll = function() {
    growShrinkLogo()
  };
  
  function growShrinkLogo() {
    var Nav = document.getElementById("navbar")
    if (document.body.scrollTop > 5 || document.documentElement.scrollTop > 5) {
      Nav.style.height = '60px';
    } else {
      Nav.style.height = '100px';
    }
  }
}
